/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Service = IDL.Variant({
  'appDevelopment' : IDL.Null,
  'webDevelopment' : IDL.Null,
  'consultancy' : IDL.Null,
  'branding' : IDL.Null,
  'productDesign' : IDL.Null,
});
export const Inquiry = IDL.Record({
  'service' : Service,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'sendInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), Service, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Service = IDL.Variant({
    'appDevelopment' : IDL.Null,
    'webDevelopment' : IDL.Null,
    'consultancy' : IDL.Null,
    'branding' : IDL.Null,
    'productDesign' : IDL.Null,
  });
  const Inquiry = IDL.Record({
    'service' : Service,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'sendInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), Service, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };