/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Inquiry {
    service: Service;
    name: string;
    email: string;
    message: string;
    timestamp: bigint;
    phone?: string;
}
export enum Service {
    appDevelopment = "appDevelopment",
    webDevelopment = "webDevelopment",
    consultancy = "consultancy",
    branding = "branding",
    productDesign = "productDesign"
}
export interface backendInterface {
    getAllInquiries(): Promise<Array<Inquiry>>;
    sendInquiry(name: string, email: string, phone: string | null, service: Service, message: string): Promise<void>;
}
import type { Inquiry as _Inquiry, Service as _Service } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInquiries();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInquiries();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendInquiry(arg0: string, arg1: string, arg2: string | null, arg3: Service, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendInquiry(arg0, arg1, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg2), to_candid_Service_n8(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendInquiry(arg0, arg1, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg2), to_candid_Service_n8(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
}
function from_candid_Inquiry_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Inquiry): Inquiry {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Service_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Service): Service {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    service: _Service;
    name: string;
    email: string;
    message: string;
    timestamp: bigint;
    phone: [] | [string];
}): {
    service: Service;
    name: string;
    email: string;
    message: string;
    timestamp: bigint;
    phone?: string;
} {
    return {
        service: from_candid_Service_n4(_uploadFile, _downloadFile, value.service),
        name: value.name,
        email: value.email,
        message: value.message,
        timestamp: value.timestamp,
        phone: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    appDevelopment: null;
} | {
    webDevelopment: null;
} | {
    consultancy: null;
} | {
    branding: null;
} | {
    productDesign: null;
}): Service {
    return "appDevelopment" in value ? Service.appDevelopment : "webDevelopment" in value ? Service.webDevelopment : "consultancy" in value ? Service.consultancy : "branding" in value ? Service.branding : "productDesign" in value ? Service.productDesign : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Inquiry>): Array<Inquiry> {
    return value.map((x)=>from_candid_Inquiry_n2(_uploadFile, _downloadFile, x));
}
function to_candid_Service_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Service): _Service {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Service): {
    appDevelopment: null;
} | {
    webDevelopment: null;
} | {
    consultancy: null;
} | {
    branding: null;
} | {
    productDesign: null;
} {
    return value == Service.appDevelopment ? {
        appDevelopment: null
    } : value == Service.webDevelopment ? {
        webDevelopment: null
    } : value == Service.consultancy ? {
        consultancy: null
    } : value == Service.branding ? {
        branding: null
    } : value == Service.productDesign ? {
        productDesign: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
